development:
  clients:
    default:
      database: simple_image_api_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: simple_image_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
